### ISSUE TITLE
Vote Roulette doesn't seem to find players in game

### ISSUE THREAD

**Issue by Reolex** [ebiggz/VoteRoulette#5]
Console	: [18:12:28 WARN]: Exception in thread "Thread-12" 
Console	: [18:12:28 WARN]: java.lang.NullPointerException
Console	: [18:12:28 WARN]: 	at com.mythicacraft.voteroulette.stats.StatManager.updateStatsWithPlayer(StatManager.java:83)
Console	: [18:12:28 WARN]: 	at com.mythicacraft.voteroulette.listeners.VoteProcessor.run(VoteProcessor.java:69)
Console	: [18:12:28 WARN]: 	at java.lang.Thread.run(Unknown Source)

I keep getting this error every time I vote? do you know of any fix?

**Comment by ebiggz** [comment]
Hi Reolex, 
This bug has been fixed in an upcoming update. 
To work around it for now, you'll need to manually create the folder that player data is saved in. If you have UUIDs enabled (in config.yml "useUUIDs"), then the folder should be called "playerdata" and saved in the path "/VoteRoulette/data/playerdata". If you have UUIDs disabled the folder is called "players" with the path "/VoteRoulette/data/players".

**Comment by Reolex** [comment]
You're the best. Super quick response too!

**Comment by ebiggz** [comment]
No worries, sorry for the bug!
